class ABCD{
    public static void main(String []args){
        int n=5;
        char ='A';
        
        for(int i=1;i<=n;i++){
            for(int j=1;j<=n;j++){
                if(i==j){
                    System.out.print(c);
                }
                else{
                    System.out.print(j);
                }
                System.out.println();
                c++;
            }
        }
    }

}